#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
my_disp="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
if [ "$#" -lt 4 ]
then
    echo "$my_disp"
else
    scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
fi
