#!/usr/bin/env bash
# Install nginx web server
TEXT="location /redirect_me {\\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\\n}\\n"
sudo apt-get -y update
sudo apt-get -y install nginx
sudo echo "Holberton School" > /var/www/html/index.html
sudo sed -i "42i $TEXT" /etc/nginx/sites-available/default
sudo service nginx start
