#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
i="1"
while [[ $i -lt 11 ]]
do
    if [ $i -eq 10 ]
    then
        echo "Hi"
    fi
    echo "Holberton School"
    i=$((i+1))
done